# Generated by Django 2.0.7 on 2018-07-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerpc', '0003_auto_20180715_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadora',
            name='activa',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
