# Generated by Django 2.0.7 on 2018-07-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerpc', '0004_computadora_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadora',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
