# Generated by Django 2.0.7 on 2018-07-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerpc', '0006_auto_20180715_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computadora',
            name='dañado',
        ),
        migrations.AddField(
            model_name='computadora',
            name='funciona',
            field=models.BooleanField(default=True),
        ),
    ]
