# Generated by Django 2.1.2 on 2018-11-18 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registerpc', '0009_auto_20180812_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadora',
            name='representante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='registerpc.Representante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='año',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
