# Generated by Django 2.1.2 on 2018-11-18 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerpc', '0010_auto_20181118_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='año',
            new_name='ano',
        ),
    ]
