# Generated by Django 2.1.2 on 2018-11-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerpc', '0011_auto_20181118_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='ano',
            field=models.BigIntegerField(max_length=1),
        ),
    ]
