# Generated by Django 2.1.2 on 2018-11-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerpc', '0013_auto_20181119_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='ano',
            new_name='año',
        ),
    ]
