# Generated by Django 2.0.7 on 2018-07-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerpc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computadora',
            name='representante',
        ),
        migrations.RemoveField(
            model_name='representante',
            name='pais',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='representante',
            name='apellido',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
