# Generated by Django 2.0.7 on 2018-07-15 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registerpc', '0002_auto_20180715_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computadora',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='computadora',
            name='estudiante',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='registerpc.Estudiante'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='representante',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='representante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='registerpc.Representante'),
            preserve_default=False,
        ),
    ]
