# Generated by Django 2.0.7 on 2018-07-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerpc', '0005_computadora_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computadora',
            name='activa',
        ),
        migrations.AddField(
            model_name='computadora',
            name='dañado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='computadora',
            name='descripcion',
            field=models.TextField(blank=True, help_text='si el equipo esta dañado por favor describa la falla'),
        ),
    ]
