# Generated by Django 2.0.7 on 2018-08-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerpc', '0007_auto_20180715_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='telefono',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='computadora',
            name='descripcion',
            field=models.TextField(blank=True, help_text='si el equipo esta dañado o no funciona por favor describa la falla'),
        ),
    ]
